# Copyright (c) 2020 Dell Inc.
---
galaxy_info:
  author: Dell EMC Networking Engineering
  description: The os9_sflow role facilitates the configuration of sflow attributes in devices running Dell EMC Networking Operating Systems.
  company: Dell Inc
  license:  Apache 2.0
  min_ansible_version: 2.2

  platforms:
  - name: os9

  galaxy_tags:
    - networking
    - dell
    - emc
    - dellemc
    - os9